# https://bandit.readthedocs.io/en/latest/config.html
# Skip test B101 because of issue https://github.com/PyCQA/bandit/issues/457
[tool.bandit]
tests = []
skips = ["B101"]

# https://github.com/psf/black#configuration
[tool.black]
line-length = 120
target-version = ["py39"]

[tool.coverage.report]
fail_under = 100
show_missing = true

# https://github.com/pytest-dev/pytest-cov
# https://github.com/nedbat/coveragepy
[tool.coverage.run]
omit = [
    "*/package/__main__.py",
]

# https://pycqa.github.io/isort/
[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 120
skip_gitignore = true

# https://mypy.readthedocs.io/en/stable/config_file.html#using-a-pyproject-toml
[tool.mypy]
mypy_path = "src"
# exclude=
show_error_codes = true
show_column_numbers = true
check_untyped_defs = true
incremental = false
warn_return_any = true
warn_redundant_casts = true
warn_unused_ignores = true
[[tool.mypy.overrides]]
module = "pytest"
ignore_missing_imports = true
[[tool.mypy.overrides]]
module = "package.*"
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_decorators = true

# https://docs.pytest.org/en/6.2.x/customize.html#configuration-file-formats
# https://docs.pytest.org/en/6.2.x/reference.html#configuration-options
# https://docs.pytest.org/en/6.2.x/reference.html#command-line-flags
[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--verbose --doctest-modules -ra --cov package"  # Consider adding --pdb
doctest_optionflags = "IGNORE_EXCEPTION_DETAIL"
testpaths = [
    "tests",
]

# https://python-semantic-release.readthedocs.io/en/latest/
[tool.semantic_release]
branch = "main"
version_variable = "src/package/__init__.py:__version__"
upload_to_pypi = false
commit_subject = "bump: release v{version}"
changelog_file = "CHANGELOG.md"
