name: Release Notifications
on:
  release:
    types: [published]

# Grant no permissions to this workflow.
permissions: {}

jobs:
  slack:
    name: Slack release notification
    # Remove the next line after your Slack app has been set up. See also:
    # https://github.com/slackapi/slack-github-action#setup-2
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@dd2c410b088af7c0dc8046f3ac9a8f4148492a95 # v1.4.4
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - name: Notify via Slack
      uses: slackapi/slack-github-action@16b6c78ee73689a627b65332b34e5d409c7299da
      with:
        payload: |
          {
            "text": "${{ github.event.repository.name }} published a new release ${{ github.event.release.tag_name }}",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*${{ github.event.repository.name }}* published a new release <${{ github.event.release.html_url }}|${{ github.event.release.tag_name }}>"
                }
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
